name: Redeploy API

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  api:
    name: API
    runs-on: ubuntu-latest
    steps:
      - name: Trigger API Deployment 🚀
        uses: indiesdev/curl@v1
        with:
          url: 'https://redeploy.heyxyz.workers.dev/?secret=${{ secrets.SECRET }}'
          method: 'GET'
          headers: '{ "Referer": "https://hey.xyz" }'
