name: Release

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 0
          token: ${{ secrets.BCHARITYFI_GH_TOKEN }}

      - name: Release
        run: ./script/release
